<?php if ($this->helper('simipwa')->IsEnableForWebsite()) : ?>
<script>
    if ('serviceWorker' in navigator && 'PushManager' in window) {
        console.log('Service Worker and Push is supported');
        var sw = "<?php echo $this->getUrl('',array('_secure' => true)); ?>" + "sw.js";
        navigator.serviceWorker.register(sw)
            .then(function(swReg) {
                console.log('Service Worker is registered', '');

                swRegistration = swReg;
                initializeUI();

            })
            .catch(function(error) {
                console.error('Service Worker Error', error);
            });
    } else {
        console.warn('Push messaging is not supported');
        console.log('Push Not Supported');
    }
</script>
<?php endif ?>