<script type="text/javascript">
    //<![CDATA[
    function sync_sw() {
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/simipwa_pwa/syncSw') ?>', {
            method: 'GET',
            onSuccess: function (transport) {

                if (transport.responseText) {
                    var data = JSON.parse(transport.responseText);
                    alert(data.message);
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>