<?php
    $collection = $this->convertTotalTracking();
?>

<div class="wrapper-tracking-pwa">
    <div class="container">
        <h1 class="tracking-page-title">PWA Analytics Dashboard</h1>
        <!--        <div class="section-tracking-pwa">-->
        <!--            <div class="tracking-pwa-item">-->
        <!--                <div class="tracking-panel">-->
        <!--                    <div class="tracking-panel-header">-->
        <!--                        <div class="panel-header-content">PWA Visited</div>-->
        <!--                    </div>-->
        <!--                    <div class="tracking-panel-body"></div>-->
        <!--                </div>-->
        <!---->
        <!--            </div>-->
        <!--            <div class="tracking-pwa-item">-->
        <!--                <div class="tracking-panel">-->
        <!--                    <div class="tracking-panel-header">-->
        <!--                        <div class="panel-header-content">Switch to Website Version</div>-->
        <!--                    </div>-->
        <!--                    <div class="tracking-panel-body"></div>-->
        <!--                </div>-->
        <!--            </div>-->
        <!--            <div class="tracking-pwa-item">-->
        <!--                <div class="tracking-panel">-->
        <!--                    <div class="tracking-panel-header">-->
        <!--                        <div class="panel-header-content">Back to Pwa Version</div>-->
        <!--                    </div>-->
        <!--                    <div class="tracking-panel-body"></div>-->
        <!--                </div>-->
        <!---->
        <!--            </div>-->
        <!--        </div>-->
        <div class="section-analytics-chart">
            <div id="chart_div" style="width: 90%; height: 400px; margin: 0 auto"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    google.charts.load('current', {'packages': ['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    var collection = { tracking :<?php echo json_encode($collection); ?>}
    function drawChart() {

        var data = [['Day', 'PWA visited', 'Switch to Website', 'Back to PWA']];
        collection.tracking.forEach(function (item) {
            data.push([item.day,item.pwa_visited,item.switch_to_website,item.back_to_pwa]);
        })
        // console.log(data);
        var data = google.visualization.arrayToDataTable(data);

        var options = {
            title: 'PWA Analytics',
            hAxis: {title: '30 day Overview', titleTextStyle: {color: '#333'}},
            vAxis: {minValue: 0}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script